### ISSUE TITLE
generate gitpod config files

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/generator-theia-extension#49]
they should look similar to gitpod config file in Theia repo

**Comment by akosyakov** [comment]
.gitpod.yml template:
```yml
image:
  file: .gitpod.dockerfile
tasks:
  - init: yarn
    command: |
      gp sync-done init
      yarn --cwd problem-inspector-extension watch
  - command: |
      gp sync-await init
      yarn --cwd browser-app watch
    name: Watch browser-app
    openMode: split-right
  - command: |
      gp sync-await init
      yarn --cwd browser-app start ..
    name: Run browser-app
    openMode: tab-after
ports:
  - port: 3000 # expose Theia port
  - port: 6080 # ignore VNC port
    onOpen: ignore
  - port: 5900 # ignore VNC port
    onOpen: ignore
github:
  prebuilds:
    branches: true
```

.gitpod.dockerfile (take up to date from Theia repo)
```dockerfile
FROM gitpod/workspace-full-vnc:latest

USER root
# Install custom tools, runtime, etc.
RUN apt-get update \
    # window manager
    && apt-get install -y jwm \
    # electron
    && apt-get install -y libgtk-3-0 libnss3 libasound2 \
    # native-keymap
    && apt-get install -y libx11-dev libxkbfile-dev \
    && apt-get clean && rm -rf /var/cache/apt/* && rm -rf /var/lib/apt/lists/* && rm -rf /tmp/*

USER gitpod
# Apply user-specific settings
RUN bash -c ". .nvm/nvm.sh \
    && nvm install 10 \
    && nvm use 10 \
    && npm install -g yarn"

# Give back control
USER root
```
